AgendaContatos/Models/ContatoViewModel.cs
using System.Collections.Generic;

namespace AgendaContatos.Models
{
    public class ContatoViewModel
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public TipoContatoViewModel TipoContato { get; set; }

        public Dominio.Contato ConverterParaDominio()
        {
            return new Dominio.Contato
            {
                Codigo = this.Codigo,
                Nome = this.Nome,
                Telefone = this.Telefone,
                TipoContato = this.TipoContato.ConverterParaDominio()
            };
        }

        public static List<ContatoViewModel> ConverterTodosDeDominioParaViewModel(List<Dominio.Contato> contatosDominio)
        {
            List<ContatoViewModel> contatosConvertidos = new List<ContatoViewModel>();

            foreach (Dominio.Contato item in contatosDominio)
            {
                contatosConvertidos.Add(new ContatoViewModel
                {
                    Codigo = item.Codigo,
                    Nome = item.Nome,
                    Telefone = item.Telefone,
                    TipoContato = TipoContatoViewModel.ConverterDeDominioParaViewModel(item.TipoContato)
                });
            }

            return contatosConvertidos;
        }

        public static ContatoViewModel ConverterDeDominioParaViewModel(Dominio.Contato contatoDominio)
        {
            return new ContatoViewModel
            {
                Codigo = contatoDominio.Codigo,
                Nome = contatoDominio.Nome,
                Telefone = contatoDominio.Telefone,
                TipoContato = TipoContatoViewModel.ConverterDeDominioParaViewModel(contatoDominio.TipoContato)
            };
        }
    }
}

AgendaContatos/Models/TipoContatoViewModel.cs
using System.Collections.Generic;

namespace AgendaContatos.Models
{
    public class TipoContatoViewModel
    {
        public int Codigo { get; set; }
        public string Descricao { get; set; }

        public Dominio.TipoContato ConverterParaDominio()
        {
            return new Dominio.TipoContato
            {
                Codigo = this.Codigo,
                Descricao = this.Descricao
            };
        }

        public static List<TipoContatoViewModel> ConverterTodosDeDominioParaViewModel(List<Dominio.TipoContato> tiposContatoDominio)
        {
            List<TipoContatoViewModel> tiposContatoConvertido = new List<TipoContatoViewModel>();

            foreach (Dominio.TipoContato item in tiposContatoDominio)
            {
                tiposContatoConvertido.Add(new TipoContatoViewModel
                {
                    Codigo = item.Codigo,
                    Descricao = item.Descricao
                });
            }

            return tiposContatoConvertido;
        }

        public static TipoContatoViewModel ConverterDeDominioParaViewModel(Dominio.TipoContato tipoContatoDominio)
        {
            return new TipoContatoViewModel
            {
                Codigo = tipoContatoDominio.Codigo,
                Descricao = tipoContatoDominio.Descricao
            };
        }
    }
}

AgendaContatos/Controllers/ContatoController.cs
using AgendaContatos.Dominio;
using AgendaContatos.Models;
using AgendaContatos.Service;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AgendaContatos.Controllers
{
    public class ContatoController : Controller
    {
        private ContatoService _service;

        public ContatoController()
        {
            _service = new ContatoService();
        }

        // GET: Contato
        public ActionResult Index()
        {
            List<ContatoViewModel> contatos = ContatoViewModel.ConverterTodosDeDominioParaViewModel(_service.ConsultaTodos());
            return View(contatos);
        }

        public RedirectToRouteResult Apagar(int id)
        {
            _service.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            ContatoViewModel tipoContato = ContatoViewModel.ConverterDeDominioParaViewModel(_service.Consulta(id));
            return View(tipoContato);
        }

        public ActionResult Novo()
        {
            return View();
        }

        public RedirectToRouteResult Salvar(ContatoViewModel contato)
        {
            Contato contatoDominio = _service.Consulta(contato.Codigo);

            if (contatoDominio != null)
            {
                _service.Alterar(contato.ConverterParaDominio());
            }
            else
            {
                _service.Inserir(contato.ConverterParaDominio());
            }

            return RedirectToAction("Index");
        }
    }
}

AgendaContatos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgendaContatos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AgendaContatos/Controllers/TipoContatoController.cs
using AgendaContatos.Dominio;
using AgendaContatos.Models;
using AgendaContatos.Service;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AgendaContatos.Controllers
{
    public class TipoContatoController : Controller
    {
        private TipoContatoService _service;

        public TipoContatoController()
        {
            _service = new TipoContatoService();
        }

        // GET: TipoContato
        public ActionResult Index()
        {
            List<TipoContatoViewModel> tiposContato = TipoContatoViewModel.ConverterTodosDeDominioParaViewModel(_service.ConsultaTodos());
            
            return View(tiposContato);
        }

        public RedirectToRouteResult Apagar(int id)
        {
            _service.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            TipoContatoViewModel tipoContato = TipoContatoViewModel.ConverterDeDominioParaViewModel(_service.Consulta(id));
            return View(tipoContato);
        }

        public ActionResult Novo()
        {
            return View();
        }

        public RedirectToRouteResult Salvar(TipoContatoViewModel tipoContato)
        {
            TipoContato tipoContatoDominio = _service.Consulta(tipoContato.Codigo);

            if (tipoContatoDominio != null)
            {
                _service.Alterar(tipoContato.ConverterParaDominio());
            }
            else
            {
                _service.Inserir(tipoContato.ConverterParaDominio());
            }

            return RedirectToAction("Index");
        }
    }
}

AgendaContatos/Views/Contato/Editar.cshtml
@model AgendaContatos.Models.ContatoViewModel

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm("Salvar", "Contato"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ContatoViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AgendaContatos/Views/Contato/Index.cshtml
@model IEnumerable<AgendaContatos.Models.ContatoViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listagem</h2>

<p>
    @Html.ActionLink("Novo", "Novo")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoContato)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoContato.Descricao)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Codigo }) |
            @Html.ActionLink("Apagar", "Apagar", new { id=item.Codigo })
        </td>
    </tr>
}

</table>

AgendaContatos/Views/Contato/Novo.cshtml
@model AgendaContatos.Models.ContatoViewModel

@{
    ViewBag.Title = "Novo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Novo</h2>


@using (Html.BeginForm("Salvar", "Contato"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model=> model.TipoContato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoContato.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoContato.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para listagem", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AgendaContatos/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AgendaContatos/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AgendaContatos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AgendaContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agenda de contatos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Agenda de contatos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contato", "Index", "Contato")</li>
                    <li>@Html.ActionLink("Tipo contato", "Index", "TipoContato")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AgendaContatos/Views/TipoContato/Editar.cshtml
@model AgendaContatos.Models.TipoContatoViewModel

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm("Salvar","TipoContato"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para listagem", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AgendaContatos/Views/TipoContato/Index.cshtml
@model IEnumerable<AgendaContatos.Models.TipoContatoViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listagem</h2>

<p>
    @Html.ActionLink("Novo", "Novo")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Codigo }) |
            @Html.ActionLink("Apagar", "Apagar", new { id=item.Codigo })
        </td>
    </tr>
}

</table>

AgendaContatos/Views/TipoContato/Novo.cshtml
@model AgendaContatos.Models.TipoContatoViewModel

@{
    ViewBag.Title = "Novo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Novo</h2>


@using (Html.BeginForm("Salvar", "TipoContato"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para listagem", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}